<?php
/*
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright  Copyright (c)  2023.  Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */

use Tigren\CustomerGroupCatalog\Helper\Data;
dd(123);

?>
<?php
//$blockFaq = $block->getLayout()->createBlock('Tigren\CustomerGroupCatalog\Block\Rule');
//$_product = $block->getProduct();
//dd($blockFaq->enableModule());
//$enable = $blockFaq->enableModule();
?>
<?php //if ($_faq = $blockFaq->getFaqData()) : ?>
<!--    --><?php //if ($enable == true) : ?>
<ul>
    <li>Main store</li>
    <li>Second store</li>
    <li>Joe store</li>
    <li>Mom store</li>
    <li>Bruh store</li>
</ul>




<!--    --><?php //endif; ?>
<?php //endif;  ?>
